### ISSUE TITLE
PDF/PS formats

### ISSUE THREAD

**Issue by mikowitz** [mikowitz/xairo.v1#16]
v1 should support PNG, PDF, PS, SVG.

PNG needs to be explicitly saved, the other three take a file location at the start and write to disk as the path develops. There is probably way to abstract this out into a single function. 

Different struct for each output format, or a field on a single struct type?

## Todo

- [x] `save_image` should save as png or `surface.finish()` correctly for each image type (this is currently handled in Rust, but might be less bulky to handle in Elixir)
- [x] `new_image` should take filename, height, width, options, determine image type from filename extension
- [x] Behaviour for image with `new`, `save` functions that delegate to NIFs correctly
- [x] Standardize `Xairo` public API with `new/4` and `save/1`

**Comment by mikowitz** [comment]
Closed in #49
